# Non-graded Challenge 5

In [1]:
import numpy as np

Apakah [ 1,3 ] adalah eigen vector dari [[1, -1], [6, 4]]? Jika iya berapakah nilai eigen value nya?

In [13]:
#membuat eigendecompotion dalam bentuk array
A = np.array([[1, -1],
            [6, 4]])
            
A

array([[ 1, -1],
       [ 6,  4]])

In [14]:
#mencarai eigen value dan eigen vector
eig_val, eig_vec = np.linalg.eig(A)

In [15]:
#menampilkan eigen value dari array
eig_val

array([2.5+1.93649167j, 2.5-1.93649167j])

nilai eigen value dari array A yaitu ([2.5+1.93649167j, 2.5-1.93649167j])

In [10]:
eig_vec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [11]:
[1/np.sqrt(2.5+1.93649167j), 3/np.sqrt(2.5+1.93649167j)]

[(0.5320844700362038-0.18197220379275678j),
 (1.5962534101086114-0.5459166113782704j)]

In [12]:
[1/np.sqrt(2.5-1.93649167j), 3/np.sqrt(2.5-1.93649167j)]

[(0.5320844700362038+0.18197220379275678j),
 (1.5962534101086114+0.5459166113782704j)]

In [17]:
np.diag(eig_val)

array([[2.5+1.93649167j, 0. +0.j        ],
       [0. +0.j        , 2.5-1.93649167j]])

In [18]:
np.linalg.inv(eig_vec)

array([[ 7.77156117e-17-1.67332005j,  5.40061725e-01-0.41833001j],
       [-7.77156117e-17+1.67332005j,  5.40061725e-01+0.41833001j]])

In [19]:
M_reconst = eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)
M_reconst

array([[ 1.+4.4408921e-16j, -1.+0.0000000e+00j],
       [ 6.-4.4408921e-16j,  4.+0.0000000e+00j]])

In [20]:
A

array([[ 1, -1],
       [ 6,  4]])

dari eigen reconstruct dapat dilihat bahwa [1,3] merupakan eigen vector dari array A karena setelah direcontruct nilai yang diperoleh sama. untuk nilai eigen value dari array A yaitu ([2.5+1.93649167j, 2.5-1.93649167j])