# Non-graded Challenge 4

In [4]:
import numpy as np

1.  Buatlah Tensor di bawah ini dengan Python:


In [12]:
#Tensor
T = np.array([
    [[[23,50], [7, 12]], 
    [[57, 67], [99, 43]]],
    [[[75, 21], [57, 12]],
    [[87, 26], [18, 24]]]])
    
T

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 24]]]])

2. Lakukan perkalian terhadap matrix berikut: 
    
    𝐴= 23 50 19 

        7 12 109 

        57 67 98 
        
    𝐵= 17

        22
        
        19


In [6]:
#memasukkan matriks dalam variabel A dan B
A = np.array([[23, 50, 19],
            [7, 12, 109],
            [57, 67, 98]])

B = np.array([[17],
            [22],
            [19]])

In [7]:
#perkalian antar matriks
C = A @ B
C

array([[1852],
       [2454],
       [4305]])

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini: 

In [8]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [9]:
#transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [10]:
#determinan
np.linalg.det(A)

131344.0000000002

In [11]:
#invers
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])